{{ if .Values.enableStandalone -}}
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    operator.synopsys.com/group-dependencies: "ConfigMap"
  labels:
    operator.synopsys.com/group-id: "Cfssl"
    app: alert
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-cfssl
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    app: alert
    name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: alert
        name: {{ .Release.Name }}
      name: {{ .Release.Name }}-cfssl
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-blackduck-alert-config
          image: {{ .Values.cfssl.image }}
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - http://localhost:8888/api/v1/cfssl/scaninfo
            failureThreshold: 10
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 10
          name: blackduck-cfssl
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              memory: {{ .Values.cfssl.limitMemory }}
            requests:
              memory: {{ .Values.cfssl.requestMemory }}
          volumeMounts:
            - mountPath: /etc/cfssl
              name: dir-cfssl
      dnsPolicy: ClusterFirst
      {{- with .Values.cfssl.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.cfssl.affinity }}
      affinity:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.cfssl.tolerations }}
      tolerations:
      {{ toYaml . | indent 2 }}
      {{- end }}
      volumes:
        - emptyDir: {}
          name: dir-cfssl
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.synopsys.com/group-dependencies: "ConfigMap"
  labels:
    operator.synopsys.com/group-id: "Cfssl"
    app: alert
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-cfssl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-8888
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: alert
    name: {{ .Release.Name }}
  type: ClusterIP
---
{{- end }}